{% set name = "clorm" %}
{% set version = "1.2.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/potassco/{{ name }}/archive/v{{ version }}.zip
  sha256: 420c33bca5153bbe1350c01638d51f10bcbe4f8ec16caec621e2e3331333a0c0

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - clingo >=5.4.0
    - python >=3.6

test:
  imports:
    - clorm
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://potassco.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: ORM interface for the Clingo ASP Solver
  description: |
    Clorm is a Python library that provides an Object Relational Mapping (ORM)
    style interface to the Clingo Answer Set Programming (ASP) solver. It
    allows facts to be asserted to, and extracted from, the ASP solver in an
    intuitive and easy to use way.
  doc_url: https://clorm.readthedocs.io/en/latest/index.html
  dev_url: https://github.com/potassco/{{ name }}

extra:
  recipe-maintainers:
    - rkaminsk
    - daveraja
